---
#-------------------------------
# General Site Settings

title: Josiah Herfurth
logo: assets/images/logo.png
logo-white: assets/images/logo-white.png
author: Josiah Herfurth
description: Creator of Spaces, Stories, & Games for People.
email: josiahherfurth@gmail.com
phone: +1 (480) 431-5565
copyright: Copyright &copy; 2022-2026 Josiah Herfurth

#-------------------------------
# Google Analytics

google-analytics: G-H8LKPKEECW

#-------------------------------
# Hero Section

hero:
  hero-title: Hi, I'm Josiah Herfurth
  hero-subtitle: Creator of Spaces, Stories, & Games for People.
  slideshow-images:
    - image: assets/images/chair-01/perspective-1.jpg
      text: light
    - image: assets/images/masterworks/necronomicon.png
      text: dark
    - image: assets/images/lost-boys/lost-boys.png
      text: light
    - image: assets/images/cat-game/cat-in-a-horror-game-5.png
      text: dark

social:
  - { icon: "ti-linkedin", link: "https://www.linkedin.com/in/josiah-herfurth" }
  - { icon: "ti-youtube", link: "https://www.youtube.com/@josiahherfurth" }

#-------------------------------
# Portfolio

portfolio-label:
  - { title: "Games", type: "games" }
  - { title: "Film", type: "film" }
  - { title: "Design", type: "design" }
